name: photo_histogram
ui: qunit
scripts:
  - "https://code.jquery.com/jquery-2.1.4.min.js"
  - "https://code.jquery.com/qunit/qunit-1.20.0.js"
  - "js/photo-histogram.js"
html: "test/zuulTemplate.html"
browsers:
  - name: ipad
    version: 5.1..latest
  - name: firefox
    version: 4..latest
  - name: iphone
    version: 5.1..latest
  - name: safari
    version: 5..latest
  - name: chrome
    version: 26..latest
  - name: internet explorer
    version: 6..latest
  - name: microsoftedge
    version: 20..latest
  - name: opera
    version: 11..latest
  - name: android
    version: 4.0..latest